<a href="https://colab.research.google.com/github/Blenkzx/LINGUAGENS-DE-PROGRAMA-O/blob/main/EXERC%C3%8DCIOPANDAS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Base de vendas
dados_vendas = {
    'cliente_id': [101, 102, 103, 101, 104, 102, 105, 103],
    'valor': [3500.75, 189.50, np.nan, 1200.00, 450.00, np.nan, 89.90, 780.50],
    'categoria': [
        'Eletronicos',
        'Livros',
        'Roupas',
        'Eletronicos',
        'Automotivo',
        'Livros',
        'Roupas',
        'Roupas',
    ],
    'data_hora': [
        '2024-01-15 10:23:00',
        '2024-01-18 14:05:00',
        '2024-02-05 09:12:00',
        '2024-02-20 16:40:00',
        '2024-03-02 11:00:00',
        '2024-03-15 18:30:00',
        '2024-04-10 08:20:00',
        '2024-04-22 13:45:00',
    ],
    'status': [
        'Concluído',
        'Concluído',
        'Pendente',
        'Concluído',
        'Cancelado',
        'Concluído',
        'Concluído',
        'Concluído',
    ],
    'email': [
        'maria@gmail.com',
        'joao@outlook.com',
        'ana@yahoo.com',
        'maria@gmail.com',
        'carlos@gmail.com',
        'joao@outlook.com',
        'lucas@empresa.com.br',
        'ana@yahoo.com',
    ],
}

# Base de clientes
dados_clientes = {
    'cliente_id': [101, 102, 103, 104, 105],
    'nome': [
        'Maria Silva',
        'Joao Souza',
        'Ana Oliveira',
        'Carlos Lima',
        'Lucas Mendes',
    ],
    'cidade': [
        'Sao Paulo',
        'Rio de Janeiro',
        'Belo Horizonte',
        'Curitiba',
        'Salvador',
    ],
}

df_vendas = pd.DataFrame(dados_vendas)
df_clientes = pd.DataFrame(dados_clientes)

## Parte 1: Diagnóstico e Limpeza (Básico)

In [2]:

print("Dimensões de df_vendas:", df_vendas.shape)
print("\nInformações de df_vendas:")
df_vendas.info()

Dimensões de df_vendas: (8, 6)

Informações de df_vendas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  8 non-null      int64
 1   valor       6 non-null      float64
 2   categoria   8 non-null      object
 3   data_hora   8 non-null      object
 4   status      8 non-null      object
 5   email       8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

In [3]:


df_vendas['valor'] = df_vendas.groupby('categoria')['valor'].transform(
    lambda x: x.fillna(x.median() if not x.isnull().all() else df_vendas['valor'].median())
)

print("\nValores nulos após o preenchimento:")
display(df_vendas[df_vendas['valor'].isnull()])
display(df_vendas.head())

Valores nulos após o preenchimento:

Empty DataFrame
Columns: [cliente_id, valor, categoria, data_hora, status, email]
Index: []

,cliente_id,valor,categoria,data_hora,status,email
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com
2,103,435.20,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com

In [4]:

transacoes_filtradas = df_vendas.query("status == 'Concluído' and valor > 500.00")

print("\nTransações com status 'Concluído' e valor superior a R$ 500,00:")
display(transacoes_filtradas)

Transações com status 'Concluído' e valor superior a R$ 500,00:

,cliente_id,valor,categoria,data_hora,status,email
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com

## Parte 2: Cruzamento e Transformação (Intermediário)

In [5]:

df_merged = pd.merge(df_vendas, df_clientes, on='cliente_id', how='left')

print("\nDataFrame após a junção:")
display(df_merged.head())

DataFrame após a junção:

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
2,103,435.20,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba

In [6]:

df_merged['media_categoria'] = df_merged.groupby('categoria')['valor'].transform('mean')

print("\nDataFrame com a coluna 'media_categoria':")
display(df_merged.head())

DataFrame com a coluna 'media_categoria':

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade,media_categoria
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro,189.500
2,103,435.20,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte,435.200
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba,450.000

In [7]:

clientes_gmail_count = df_merged['email'].str.contains('@gmail.com', na=False).sum()

print(f"\nNúmero de clientes que usam @gmail.com: {clientes_gmail_count}")

Número de clientes que usam @gmail.com: 3

## Parte 3: Análise Temporal e Agregação (Intermediário)

In [11]:

df_merged['data_hora'] = pd.to_datetime(df_merged['data_hora'])
df_merged['mes_extenso'] = df_merged['data_hora'].dt.month_name()
df_merged['dia_da_semana'] = df_merged['data_hora'].dt.day_name()

print("\nDataFrame com colunas de tempo extraídas:")
display(df_merged[['data_hora', 'mes_extenso', 'dia_da_semana']].head())

DataFrame com colunas de tempo extraídas:

            data_hora mes_extenso dia_da_semana
0 2024-01-15 10:23:00     January        Monday
1 2024-01-18 14:05:00     January      Thursday
2 2024-02-05 09:12:00    February        Monday
3 2024-02-20 16:40:00    February       Tuesday
4 2024-03-02 11:00:00       March      Saturday

In [9]:

pivot_table_vendas = pd.pivot_table(
    df_merged,
    values='valor',
    index='categoria',
    columns='cidade',
    aggfunc='sum',
    fill_value=0
)

print("\nTabela Dinâmica de Vendas por Categoria e Cidade:")
display(pivot_table_vendas)

Tabela Dinâmica de Vendas por Categoria e Cidade:

cidade       Belo Horizonte  Curitiba  Rio de Janeiro  Salvador  Sao Paulo
categoria
Automotivo              0.0     450.0             0.0       0.0       0.00
Eletronicos             0.0       0.0             0.0       0.0    4700.75
Livros                  0.0       0.0           379.0       0.0       0.00
Roupas               1215.7       0.0             0.0      89.9       0.00